const abecedario = [
  {
    id: 1,
    titulo: 'Letra A',
    completo: false,
    contenido: 'A a',
  },
  {
    id: 2,
    titulo: 'Letra B',
    completo: false,
    contenido: 'B b',
  },
  {
    id: 3,
    titulo: 'Letra C',
    completo: false,
    contenido: 'C c',
  },
  {
    id: 4,
    titulo: 'Letra D',
    completo: false,
    contenido: 'D d',
  },
  {
    id: 5,
    titulo: 'Letra E',
    completo: false,
    contenido: 'E e',
  },
  {
    id: 6,
    titulo: 'Letra F',
    completo: false,
    contenido: 'F f',
  },
  {
    id: 7,
    titulo: 'Letra G',
    completo: false,
    contenido: 'G g',
  },
  {
    id: 8,
    titulo: 'Letra H',
    completo: false,
    contenido: 'H h',
  },
  {
    id: 9,
    titulo: 'Letra I',
    completo: false,
    contenido: 'I i',
  },
  {
    id: 10,
    titulo: 'Letra J',
    completo: false,
    contenido: 'J j',
  },
  {
    id: 11,
    titulo: 'Letra K',
    completo: false,
    contenido: 'K k',
  },
  {
    id: 12,
    titulo: 'Letra L',
    completo: false,
    contenido: 'L l',
  },
  {
    id: 13,
    titulo: 'Letra M',
    completo: false,
    contenido: 'M m',
  },
  {
    id: 14,
    titulo: 'Letra N',
    completo: false,
    contenido: 'N n',
  },
  {
    id: 15,
    titulo: 'Letra Ñ',
    completo: false,
    contenido: 'Ñ ñ',
  },
  {
    id: 16,
    titulo: 'Letra O',
    completo: false,
    contenido: 'O o',
  },
  {
    id: 17,
    titulo: 'Letra P',
    completo: false,
    contenido: 'P p',
  },
  {
    id: 18,
    titulo: 'Letra Q',
    completo: false,
    contenido: 'Q q',
  },
  {
    id: 19,
    titulo: 'Letra R',
    completo: false,
    contenido: 'R r',
  },
  {
    id: 20,
    titulo: 'Letra S',
    completo: false,
    contenido: 'S s',
  },
  {
    id: 21,
    titulo: 'Letra T',
    completo: false,
    contenido: 'T t',
  },
  {
    id: 22,
    titulo: 'Letra U',
    completo: false,
    contenido: 'U u',
  },
  {
    id: 23,
    titulo: 'Letra V',
    completo: false,
    contenido: 'V v',
  },
  {
    id: 24,
    titulo: 'Letra W',
    completo: false,
    contenido: 'W w',
  },
  {
    id: 25,
    titulo: 'Letra X',
    completo: false,
    contenido: 'X x',
  },
  {
    id: 26,
    titulo: 'Letra Y',
    completo: false,
    contenido: 'Y y',
  },
  {
    id: 27,
    titulo: 'Letra Z',
    completo: false,
    contenido: 'Z z',
  },
];

export default abecedario;
