const familia = [
  {
    id: 1,
    titulo: 'Mamá',
    completo: false,
    contenido: 'mamá',
    imagen: require('../../vista/recursos/jugar/mama.png'),
  },
  {
    id: 2,
    titulo: 'Papá',
    completo: false,
    contenido: 'papá',
    imagen: require('../../vista/recursos/jugar/papa.png'),
  },
  {
    id: 3,
    titulo: 'Hermano',
    completo: false,
    contenido: 'hermano',
    imagen: require('../../vista/recursos/jugar/hermano.png'),
  },
  {
    id: 4,
    titulo: 'Hermana',
    completo: false,
    contenido: 'hermana',
    imagen: require('../../vista/recursos/jugar/hermana.png'),
  },
  {
    id: 5,
    titulo: 'Abuelo',
    completo: false,
    contenido: 'abuelo',
    imagen: require('../../vista/recursos/jugar/abuelo.png'),
  },
  {
    id: 6,
    titulo: 'Abuela',
    completo: false,
    contenido: 'abuela',
    imagen: require('../../vista/recursos/jugar/abuela.png'),
  },
  {
    id: 7,
    titulo: 'Perro',
    completo: false,
    contenido: 'perro',
    imagen: require('../../vista/recursos/jugar/perro.png'),
  },
  {
    id: 8,
    titulo: 'Gato',
    completo: false,
    contenido: 'gato',
    imagen: require('../../vista/recursos/jugar/gato.png'),
  },
];

const objetos_familiares = [
  {
    id: 1,
    titulo: 'Silla',
    completo: false,
    contenido: 'silla',
    imagen: require('../../vista/recursos/jugar/silla.png'),
  },
  {
    id: 2,
    titulo: 'Ventana',
    completo: false,
    contenido: 'ventana',
    imagen: require('../../vista/recursos/jugar/ventana.png'),
  },
  {
    id: 3,
    titulo: 'Reloj',
    completo: false,
    contenido: 'reloj',
    imagen: require('../../vista/recursos/jugar/reloj.png'),
  },
  {
    id: 4,
    titulo: 'Televisión',
    completo: false,
    contenido: 'televisión',
    imagen: require('../../vista/recursos/jugar/television.png'),
  },
  {
    id: 5,
    titulo: 'Mesa',
    completo: false,
    contenido: 'mesa',
    imagen: require('../../vista/recursos/jugar/mesa.png'),
  },
  {
    id: 6,
    titulo: 'Pared',
    completo: false,
    contenido: 'pared',
    imagen: require('../../vista/recursos/jugar/pared.png'),
  },
  {
    id: 7,
    titulo: 'Cocina',
    completo: false,
    contenido: 'cocina',
    imagen: require('../../vista/recursos/jugar/cocina.png'),
  },
  {
    id: 8,
    titulo: 'Puerta',
    completo: false,
    contenido: 'puerta',
    imagen: require('../../vista/recursos/jugar/puerta.png'),
  },
  {
    id: 9,
    titulo: 'Nevera',
    completo: false,
    contenido: 'nevera',
    imagen: require('../../vista/recursos/jugar/nevera.png'),
  },
];

const objetos_personales = [
  {
    id: 1,
    titulo: 'Plato',
    completo: false,
    contenido: 'plato',
    imagen: require('../../vista/recursos/jugar/plato.png'),
  },
  {
    id: 2,
    titulo: 'Sombrero',
    completo: false,
    contenido: 'sombrero',
    imagen: require('../../vista/recursos/jugar/sombrero.png'),
  },
  {
    id: 3,
    titulo: 'Pijama',
    completo: false,
    contenido: 'pijama',
    imagen: require('../../vista/recursos/jugar/pijama.png'),
  },
  {
    id: 4,
    titulo: 'Zapatos',
    completo: false,
    contenido: 'zapatos',
    imagen: require('../../vista/recursos/jugar/zapatos.png'),
  },
  {
    id: 5,
    titulo: 'Pantalón',
    completo: false,
    contenido: 'pantalón',
    imagen: require('../../vista/recursos/jugar/pantalon.png'),
  },
  {
    id: 6,
    titulo: 'Pelota',
    completo: false,
    contenido: 'pelota',
    imagen: require('../../vista/recursos/jugar/pelota.png'),
  },
  {
    id: 7,
    titulo: 'Camisa',
    completo: false,
    contenido: 'camisa',
    imagen: require('../../vista/recursos/jugar/camisa.png'),
  },
  {
    id: 8,
    titulo: 'Vestido',
    completo: false,
    contenido: 'vestido',
    imagen: require('../../vista/recursos/jugar/vestido.png'),
  },
];

const acciones = [
  {
    id: 1,
    titulo: 'Reír',
    completo: false,
    contenido: 'reír',
    imagen: require('../../vista/recursos/jugar/reir.png'),
  },
  {
    id: 2,
    titulo: 'Llorar',
    completo: false,
    contenido: 'llorar',
    imagen: require('../../vista/recursos/jugar/llorar.png'),
  },
  {
    id: 3,
    titulo: 'Sentarse',
    completo: false,
    contenido: 'sentarse',
    imagen: require('../../vista/recursos/jugar/sentarse.png'),
  },
  {
    id: 4,
    titulo: 'Caminar',
    completo: false,
    contenido: 'caminar',
    imagen: require('../../vista/recursos/jugar/caminar.png'),
  },
  {
    id: 5,
    titulo: 'Pasear',
    completo: false,
    contenido: 'pasear',
    imagen: require('../../vista/recursos/jugar/pasear.png'),
  },
  {
    id: 6,
    titulo: 'Leer',
    completo: false,
    contenido: 'leer',
    imagen: require('../../vista/recursos/jugar/leer.png'),
  },
  {
    id: 7,
    titulo: 'Comer',
    completo: false,
    contenido: 'comer',
    imagen: require('../../vista/recursos/jugar/comer.png'),
  },
  {
    id: 8,
    titulo: 'Saltar',
    completo: false,
    contenido: 'saltar',
    imagen: require('../../vista/recursos/jugar/saltar.png'),
  },
  {
    id: 9,
    titulo: 'Dormir',
    completo: false,
    contenido: 'dormir',
    imagen: require('../../vista/recursos/jugar/dormir.png'),
  },
  {
    id: 10,
    titulo: 'Jugar',
    completo: false,
    contenido: 'jugar',
    imagen: require('../../vista/recursos/jugar/jugar.png'),
  },
];

const entorno = [
  {
    id: 1,
    titulo: 'Familia',
    completo: false,
    opciones: familia,
  },
  {
    id: 2,
    titulo: 'Objetos Personales',
    completo: false,
    opciones: objetos_personales,
  },
  {
    id: 3,
    titulo: 'Objetos Familiares',
    completo: false,
    opciones: objetos_familiares,
  },
  {
    id: 4,
    titulo: 'Acciones',
    completo: false,
    opciones: acciones,
  },
];

export default entorno;
